[package]
name = "waydoodle"
version = "0.1.0"
edition = "2024"
description = "A minimalistic screen annotation tool for Wayland"
license = "MIT"
repository = "https://github.com/dessaya/waydoodle"
authors = ["Diego Essaya"]
keywords = ["wayland", "annotation", "drawing", "presentation"]
categories = ["graphics"]

[dependencies]
smithay-client-toolkit = { version = "0.20", features = ["calloop", "xkbcommon"] }
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client"] }
log = "0.4"
env_logger = "0.11"
calloop = { version = "0.14", features = ["signals"] }
